version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://root:dYZcF2IOryvmn1uL6DDasohc@kazbek.liara.cloud:34054/postgres
    entrypoint: ["/app/start.sh"]
    command: ["/app/main"]

